env:
  - GO111MODULE=on

before:
  hooks:
  - go mod download

builds:
  -
    main: ./cmd/amass/
    binary: amass
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

archives:
  -
    name_template: "amass_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macos
      386: i386
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE
      - README.md
      - doc/*
      - wordlists/*

checksum:
  name_template: "amass_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
    - '^doc:'
    - '^test:'

release:
  github:
    owner: OWASP
    name: Amass

dockers:
  -
    dockerfile: Dockerfile
    image_templates:
      - "caffix/amass:v{{ .Major }}"
      - "caffix/amass:v{{ .Major }}.{{ .Minor }}"
      - "caffix/amass:{{ .Tag }}"
      - "caffix/amass:latest"

brews:
  -
    name: amass
    github:
      owner: caffix
      name: homebrew-amass
    url_template: "https://github.com/OWASP/Amass/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: caffix
      email: caffix@users.noreply.github.com
    folder: Formula
    homepage: "https://www.owasp.org/index.php/OWASP_Amass_Project"
    description: "In-depth DNS Enumeration and Network Mapping"

snapcrafts:
  -
    name: amass
    # Remember you need to `snapcraft login` first.
    publish: true
    summary: In-depth DNS Enumeration and Network Mapping.
    description: The OWASP Amass Project has developed a tool to help information security professionals perform network mapping of attack surfaces and external asset discovery using open source information gathering and active reconnaissance techniques.
    grade: stable
    confinement: strict
    # Your app's license, based on SPDX license expressions: https://spdx.org/licenses
    license: Apache-2.0	

    apps:
      amass:
        plugs: ["home", "network", "removable-media"]
#        plugs: ["home", "network", "removable-media", "personal-files"]

#    plugs:
#      personal-files:
#        read:
#        - $HOME/.amass
#        write:
#        - $HOME/.amass
