---
version: '3'
services:
  db:
    image: postgres
    ports:
    - 127.0.0.1:5432:5432
    environment:
    - POSTGRES_DB=registry
  http:
    build: .
    ports:
    - 127.0.0.1:8080:8000
    environment:
    - DATABASE_URL=postgres://postgres:postgres@db/registry
...
