language: python
dist: xenial
python:
- '3.7'
install:
- python setup.py install
script:
- pytest
deploy:
  provider: pypi
  user: "iojw"
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  password:
    secure: "PLeMNiue2FW+EmTu7OoxscnIsy3XnByWQn1eGX84c7xoV33P7EWLtYvm2PQ4QMtNGtMFPyaExCxDYrGVcCpkU2C8lcVJpi6gPV/9WyDmuiQ8R/s7oxXIZSy2FHxApkkxPCPzoJw8dSKKT/JUHfLIQMNbAqOC4p4LcKkzfDuIsw1Ddau+pIx3ukC+DeiQcG3WzzP2OS715TII3KCMuwDWZeqrXwxOMwJIas8SD+cuOW56NzUthasprMxbmig9EgTPh+ie1cK6aYqHJCHqd7g0Kz3PB2CSw4svjoEg2pUcZxOTvl1tH6ER0WG4vkkrbUX/dVOsasba291xvbkDKlGRCdLAOPFqQB2a4vilcx1d6fBDuFn2tIx0qc0qLkpGEsqK5r4QA80adaQN+ymG64TYxC6bFXjTTjIslwwlRt2Jws2jgfV5XhrE/rJBEmbz9vHUUdTPSkYloUZJi3oE+RRvUnIk5Rkx74eYutI8mYTRL1ANZic5CRBlCUE5DnkjH3ZosWOUY/9OqsNT+TJCPV4j9NLuyEQiX4a2ilmKRpc2qsHPz9+UcH+ELDrZarNu2UQlIRvFMrkIWunhxUiJKYcLgA6ScYIaSX62U0GJzZwiPfd8P/qqzi9JGMB+vL+hzA3rm/F5DtYEl/17BQxgchNjNARVPqAuy4wgNgLMcPVIvaI="
