[package]
name = "sn0int"
version = "0.12.0"
description = "Semi-automatic OSINT framework and package manager"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/sn0int"
categories = ["command-line-utilities"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "kpcyrd/sn0int" }

[workspace]
members = ["sn0int-registry/sn0int-common",
           "sn0int-registry"]

[features]
sqlite-bundled = ["libsqlite3-sys/bundled"]

[dependencies]
sn0int-common = { version="0.7.0", path="sn0int-registry/sn0int-common" }
rustyline = "5.0"
log = "0.4"
env_logger = "0.6"
hlua-badtouch = "0.4"
structopt = "0.2"
failure = "0.1"
rand = "0.7"
colored = "1.6"
lazy_static = "1.0"
shellwords = "1.0"
publicsuffix = { version="1.5", default-features=false }
diesel = { version = "1.0.0", features = ["sqlite", "chrono"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }
libsqlite3-sys = "0.12.0"
chrono = { version = "0.4", features = ["serde"] }
dirs = "2.0"
url = "1.7"
#chrootable-https = { path = "../chrootable-https" }
chrootable-https = "0.10"
rustls = { version="0.15", features=["dangerous_configuration"] }
webpki = "0.19"
webpki-roots = "0.16.0"
pem = "0.6.0"
base64 = "0.10"
data-encoding = "2.1.2"
kuchiki = "0.7.2"
serde_urlencoded = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
crossbeam-channel = "0.3"
ctrlc = "3.1"
opener = "0.4"
separator = "0.4"
maplit = "1.0.1"
sloppy-rfc4880 = "0.1.5"
regex = "1.0"
toml = "0.5"
maxminddb = "0.13"
tar = "0.4.17"
libflate = "0.1.14"
threadpool = "1.7"
x509-parser = "0.5.0"
der-parser = "2.0"
atty = "0.2"
bufstream = "0.1.4"
tokio = "0.1.14"
semver = "0.9"
bytes = "0.4"
xml-rs = "0.8"
bytesize = "1.0"
ipnetwork = "0.14"

digest = "0.8.0"
bs58 = "0.2.2"
blake2 = "0.8.0"
md-5 = "0.8.0"
sha-1 = "0.8.1"
sha2 = "0.8.0"
sha3 = "0.8.0"
hmac = "0.7"

image = "0.22"
kamadak-exif = "0.3.1"
walkdir = "2.2"
nude = "0.2"

[target.'cfg(target_os="linux")'.dependencies]
caps = "0.3"
#syscallz = { path="../syscallz-rs" }
syscallz = "0.11"
nix = "0.14"

[target.'cfg(target_os="openbsd")'.dependencies]
pledge = "0.3.1"
unveil = "0.2.0"

[dev-dependencies]
#boxxy = { path = "../boxxy-rs" }
boxxy = "0.10"
tempfile = "3.0"
