# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/creepy.ui'
#
# Created: Mon Oct 19 00:14:19 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreepyMainWindow(object):
    def setupUi(self, CreepyMainWindow):
        CreepyMainWindow.setObjectName(_fromUtf8("CreepyMainWindow"))
        CreepyMainWindow.resize(1463, 864)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreepyMainWindow.sizePolicy().hasHeightForWidth())
        CreepyMainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../creepy/include/Eye_of_Sauron_by_Blood_Solice.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreepyMainWindow.setWindowIcon(icon)
        CreepyMainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(CreepyMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.centralStackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralStackedWidget.sizePolicy().hasHeightForWidth())
        self.centralStackedWidget.setSizePolicy(sizePolicy)
        self.centralStackedWidget.setAutoFillBackground(True)
        self.centralStackedWidget.setObjectName(_fromUtf8("centralStackedWidget"))
        self.mapPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapPage.sizePolicy().hasHeightForWidth())
        self.mapPage.setSizePolicy(sizePolicy)
        self.mapPage.setObjectName(_fromUtf8("mapPage"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.mapPage)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mapWebView = QtWebKit.QWebView(self.mapPage)
        self.mapWebView.setAutoFillBackground(True)
        self.mapWebView.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.mapWebView.setObjectName(_fromUtf8("mapWebView"))
        self.verticalLayout_4.addWidget(self.mapWebView)
        self.centralStackedWidget.addWidget(self.mapPage)
        self.analysisPage = QtGui.QWidget()
        self.analysisPage.setObjectName(_fromUtf8("analysisPage"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.analysisPage)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.analysisWebView = QtWebKit.QWebView(self.analysisPage)
        self.analysisWebView.setObjectName(_fromUtf8("analysisWebView"))
        self.verticalLayout_6.addWidget(self.analysisWebView)
        self.centralStackedWidget.addWidget(self.analysisPage)
        self.verticalLayout_2.addWidget(self.centralStackedWidget)
        CreepyMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CreepyMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1463, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCreepy = QtGui.QMenu(self.menubar)
        self.menuCreepy.setObjectName(_fromUtf8("menuCreepy"))
        self.menuNewProject = QtGui.QMenu(self.menuCreepy)
        self.menuNewProject.setObjectName(_fromUtf8("menuNewProject"))
        self.menuExport = QtGui.QMenu(self.menuCreepy)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuFilters = QtGui.QMenu(self.menubar)
        self.menuFilters.setObjectName(_fromUtf8("menuFilters"))
        CreepyMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CreepyMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CreepyMainWindow.setStatusBar(self.statusbar)
        self.dockWLocationsList = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWLocationsList.setMinimumSize(QtCore.QSize(250, 127))
        self.dockWLocationsList.setObjectName(_fromUtf8("dockWLocationsList"))
        self.dockWLocationsListContents = QtGui.QWidget()
        self.dockWLocationsListContents.setObjectName(_fromUtf8("dockWLocationsListContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWLocationsListContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.locationsTableView = QtGui.QTableView(self.dockWLocationsListContents)
        self.locationsTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.locationsTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.locationsTableView.setObjectName(_fromUtf8("locationsTableView"))
        self.locationsTableView.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.locationsTableView)
        self.dockWLocationsList.setWidget(self.dockWLocationsListContents)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWLocationsList)
        self.dockWProjects = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWProjects.setMinimumSize(QtCore.QSize(200, 300))
        self.dockWProjects.setStyleSheet(_fromUtf8(""))
        self.dockWProjects.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWProjects.setObjectName(_fromUtf8("dockWProjects"))
        self.dockWProjectsContents = QtGui.QWidget()
        self.dockWProjectsContents.setObjectName(_fromUtf8("dockWProjectsContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWProjectsContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.treeViewProjects = QtGui.QTreeView(self.dockWProjectsContents)
        self.treeViewProjects.setObjectName(_fromUtf8("treeViewProjects"))
        self.verticalLayout_3.addWidget(self.treeViewProjects)
        self.dockWProjects.setWidget(self.dockWProjectsContents)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWProjects)
        self.dockWCurrentLocationDetails = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWCurrentLocationDetails.setObjectName(_fromUtf8("dockWCurrentLocationDetails"))
        self.dockWCurrentTargetDetailsContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWCurrentTargetDetailsContents.sizePolicy().hasHeightForWidth())
        self.dockWCurrentTargetDetailsContents.setSizePolicy(sizePolicy)
        self.dockWCurrentTargetDetailsContents.setObjectName(_fromUtf8("dockWCurrentTargetDetailsContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWCurrentTargetDetailsContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.currentTargetDetailsDetailsDateLabel = QtGui.QLabel(self.dockWCurrentTargetDetailsContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTargetDetailsDetailsDateLabel.sizePolicy().hasHeightForWidth())
        self.currentTargetDetailsDetailsDateLabel.setSizePolicy(sizePolicy)
        self.currentTargetDetailsDetailsDateLabel.setTextFormat(QtCore.Qt.RichText)
        self.currentTargetDetailsDetailsDateLabel.setObjectName(_fromUtf8("currentTargetDetailsDetailsDateLabel"))
        self.horizontalLayout_2.addWidget(self.currentTargetDetailsDetailsDateLabel)
        self.currentTargetDetailsDateValue = QtGui.QLabel(self.dockWCurrentTargetDetailsContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTargetDetailsDateValue.sizePolicy().hasHeightForWidth())
        self.currentTargetDetailsDateValue.setSizePolicy(sizePolicy)
        self.currentTargetDetailsDateValue.setText(_fromUtf8(""))
        self.currentTargetDetailsDateValue.setObjectName(_fromUtf8("currentTargetDetailsDateValue"))
        self.horizontalLayout_2.addWidget(self.currentTargetDetailsDateValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.currentTargetDetailsLocationLabel = QtGui.QLabel(self.dockWCurrentTargetDetailsContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTargetDetailsLocationLabel.sizePolicy().hasHeightForWidth())
        self.currentTargetDetailsLocationLabel.setSizePolicy(sizePolicy)
        self.currentTargetDetailsLocationLabel.setObjectName(_fromUtf8("currentTargetDetailsLocationLabel"))
        self.horizontalLayout_3.addWidget(self.currentTargetDetailsLocationLabel)
        self.currentTargetDetailsLocationValue = QtGui.QLabel(self.dockWCurrentTargetDetailsContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTargetDetailsLocationValue.sizePolicy().hasHeightForWidth())
        self.currentTargetDetailsLocationValue.setSizePolicy(sizePolicy)
        self.currentTargetDetailsLocationValue.setText(_fromUtf8(""))
        self.currentTargetDetailsLocationValue.setObjectName(_fromUtf8("currentTargetDetailsLocationValue"))
        self.horizontalLayout_3.addWidget(self.currentTargetDetailsLocationValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.currentTargetDetailsSourceLabel = QtGui.QLabel(self.dockWCurrentTargetDetailsContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTargetDetailsSourceLabel.sizePolicy().hasHeightForWidth())
        self.currentTargetDetailsSourceLabel.setSizePolicy(sizePolicy)
        self.currentTargetDetailsSourceLabel.setObjectName(_fromUtf8("currentTargetDetailsSourceLabel"))
        self.horizontalLayout_4.addWidget(self.currentTargetDetailsSourceLabel)
        self.currentTargetDetailsSourceValue = QtGui.QLabel(self.dockWCurrentTargetDetailsContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTargetDetailsSourceValue.sizePolicy().hasHeightForWidth())
        self.currentTargetDetailsSourceValue.setSizePolicy(sizePolicy)
        self.currentTargetDetailsSourceValue.setText(_fromUtf8(""))
        self.currentTargetDetailsSourceValue.setObjectName(_fromUtf8("currentTargetDetailsSourceValue"))
        self.horizontalLayout_4.addWidget(self.currentTargetDetailsSourceValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.currentTargetDetailsContextLabel = QtGui.QLabel(self.dockWCurrentTargetDetailsContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTargetDetailsContextLabel.sizePolicy().hasHeightForWidth())
        self.currentTargetDetailsContextLabel.setSizePolicy(sizePolicy)
        self.currentTargetDetailsContextLabel.setObjectName(_fromUtf8("currentTargetDetailsContextLabel"))
        self.horizontalLayout_5.addWidget(self.currentTargetDetailsContextLabel)
        self.currentTargetDetailsContextValue = QtGui.QLabel(self.dockWCurrentTargetDetailsContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTargetDetailsContextValue.sizePolicy().hasHeightForWidth())
        self.currentTargetDetailsContextValue.setSizePolicy(sizePolicy)
        self.currentTargetDetailsContextValue.setText(_fromUtf8(""))
        self.currentTargetDetailsContextValue.setTextFormat(QtCore.Qt.RichText)
        self.currentTargetDetailsContextValue.setWordWrap(True)
        self.currentTargetDetailsContextValue.setOpenExternalLinks(True)
        self.currentTargetDetailsContextValue.setObjectName(_fromUtf8("currentTargetDetailsContextValue"))
        self.horizontalLayout_5.addWidget(self.currentTargetDetailsContextValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.dockWCurrentLocationDetails.setWidget(self.dockWCurrentTargetDetailsContents)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWCurrentLocationDetails)
        self.mainToolbar = QtGui.QToolBar(CreepyMainWindow)
        self.mainToolbar.setObjectName(_fromUtf8("mainToolbar"))
        CreepyMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolbar)
        self.locationsActionsToolbar = QtGui.QToolBar(CreepyMainWindow)
        self.locationsActionsToolbar.setObjectName(_fromUtf8("locationsActionsToolbar"))
        CreepyMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.locationsActionsToolbar)
        self.dockWLogging = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWLogging.setObjectName(_fromUtf8("dockWLogging"))
        self.dockWLoggingContents = QtGui.QWidget()
        self.dockWLoggingContents.setObjectName(_fromUtf8("dockWLoggingContents"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.dockWLoggingContents)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.loggingContents = QtGui.QTextEdit(self.dockWLoggingContents)
        self.loggingContents.setObjectName(_fromUtf8("loggingContents"))
        self.verticalLayout_9.addWidget(self.loggingContents)
        self.dockWLogging.setWidget(self.dockWLoggingContents)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWLogging)
        self.actionExportKML = QtGui.QAction(CreepyMainWindow)
        self.actionExportKML.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/blue-document-export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportKML.setIcon(icon1)
        self.actionExportKML.setObjectName(_fromUtf8("actionExportKML"))
        self.actionExportCSV = QtGui.QAction(CreepyMainWindow)
        self.actionExportCSV.setIcon(icon1)
        self.actionExportCSV.setObjectName(_fromUtf8("actionExportCSV"))
        self.actionExit = QtGui.QAction(CreepyMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionReportProblem = QtGui.QAction(CreepyMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/exclamation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReportProblem.setIcon(icon3)
        self.actionReportProblem.setObjectName(_fromUtf8("actionReportProblem"))
        self.actionAbout = QtGui.QAction(CreepyMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/creepy")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionPluginsConfiguration = QtGui.QAction(CreepyMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/application-sidebar-list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPluginsConfiguration.setIcon(icon5)
        self.actionPluginsConfiguration.setObjectName(_fromUtf8("actionPluginsConfiguration"))
        self.actionLocations_List = QtGui.QAction(CreepyMainWindow)
        self.actionLocations_List.setCheckable(True)
        self.actionLocations_List.setChecked(True)
        self.actionLocations_List.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionLocations_List.setObjectName(_fromUtf8("actionLocations_List"))
        self.actionResult_Details = QtGui.QAction(CreepyMainWindow)
        self.actionResult_Details.setCheckable(True)
        self.actionResult_Details.setChecked(True)
        self.actionResult_Details.setObjectName(_fromUtf8("actionResult_Details"))
        self.actionAvailable_Plugins = QtGui.QAction(CreepyMainWindow)
        self.actionAvailable_Plugins.setCheckable(True)
        self.actionAvailable_Plugins.setChecked(True)
        self.actionAvailable_Plugins.setObjectName(_fromUtf8("actionAvailable_Plugins"))
        self.actionSettings = QtGui.QAction(CreepyMainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionNewPersonProject = QtGui.QAction(CreepyMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewPersonProject.setIcon(icon6)
        self.actionNewPersonProject.setObjectName(_fromUtf8("actionNewPersonProject"))
        self.actionNewLocationBasedProject = QtGui.QAction(CreepyMainWindow)
        self.actionNewLocationBasedProject.setObjectName(_fromUtf8("actionNewLocationBasedProject"))
        self.actionAnalyzeCurrentProject = QtGui.QAction(CreepyMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/target")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalyzeCurrentProject.setIcon(icon7)
        self.actionAnalyzeCurrentProject.setObjectName(_fromUtf8("actionAnalyzeCurrentProject"))
        self.actionDrawCurrentProject = QtGui.QAction(CreepyMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/map")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDrawCurrentProject.setIcon(icon8)
        self.actionDrawCurrentProject.setObjectName(_fromUtf8("actionDrawCurrentProject"))
        self.actionFilterLocationsDate = QtGui.QAction(CreepyMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/calendar-day.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilterLocationsDate.setIcon(icon9)
        self.actionFilterLocationsDate.setObjectName(_fromUtf8("actionFilterLocationsDate"))
        self.actionFilterLocationsPosition = QtGui.QAction(CreepyMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/marker.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilterLocationsPosition.setIcon(icon10)
        self.actionFilterLocationsPosition.setObjectName(_fromUtf8("actionFilterLocationsPosition"))
        self.actionRemoveFilters = QtGui.QAction(CreepyMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/minus")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemoveFilters.setIcon(icon11)
        self.actionRemoveFilters.setObjectName(_fromUtf8("actionRemoveFilters"))
        self.actionShowHeatMap = QtGui.QAction(CreepyMainWindow)
        self.actionShowHeatMap.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/fire.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowHeatMap.setIcon(icon12)
        self.actionShowHeatMap.setObjectName(_fromUtf8("actionShowHeatMap"))
        self.actionLocation_Actions = QtGui.QAction(CreepyMainWindow)
        self.actionLocation_Actions.setObjectName(_fromUtf8("actionLocation_Actions"))
        self.actionMain_Toolbar = QtGui.QAction(CreepyMainWindow)
        self.actionMain_Toolbar.setObjectName(_fromUtf8("actionMain_Toolbar"))
        self.actionDeleteCurrentProject = QtGui.QAction(CreepyMainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/minus-circle")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteCurrentProject.setIcon(icon13)
        self.actionDeleteCurrentProject.setObjectName(_fromUtf8("actionDeleteCurrentProject"))
        self.actionExportFilteredKML = QtGui.QAction(CreepyMainWindow)
        self.actionExportFilteredKML.setIcon(icon1)
        self.actionExportFilteredKML.setObjectName(_fromUtf8("actionExportFilteredKML"))
        self.actionExportFilteredCSV = QtGui.QAction(CreepyMainWindow)
        self.actionExportFilteredCSV.setIcon(icon1)
        self.actionExportFilteredCSV.setObjectName(_fromUtf8("actionExportFilteredCSV"))
        self.actionReanalyzeCurrentProject = QtGui.QAction(CreepyMainWindow)
        self.actionReanalyzeCurrentProject.setIcon(icon7)
        self.actionReanalyzeCurrentProject.setObjectName(_fromUtf8("actionReanalyzeCurrentProject"))
        self.actionCheckUpdates = QtGui.QAction(CreepyMainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/globe.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheckUpdates.setIcon(icon14)
        self.actionCheckUpdates.setObjectName(_fromUtf8("actionCheckUpdates"))
        self.actionCompareProjects = QtGui.QAction(CreepyMainWindow)
        self.actionCompareProjects.setObjectName(_fromUtf8("actionCompareProjects"))
        self.actionFilterLocationsCustom = QtGui.QAction(CreepyMainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/counter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilterLocationsCustom.setIcon(icon15)
        self.actionFilterLocationsCustom.setObjectName(_fromUtf8("actionFilterLocationsCustom"))
        self.actionNewPlaceProject = QtGui.QAction(CreepyMainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/globe-green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewPlaceProject.setIcon(icon16)
        self.actionNewPlaceProject.setObjectName(_fromUtf8("actionNewPlaceProject"))
        self.actionFilterInaccurateLocations = QtGui.QAction(CreepyMainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/marker_inaccurate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilterInaccurateLocations.setIcon(icon17)
        self.actionFilterInaccurateLocations.setObjectName(_fromUtf8("actionFilterInaccurateLocations"))
        self.menuNewProject.addAction(self.actionNewPersonProject)
        self.menuNewProject.addAction(self.actionNewPlaceProject)
        self.menuExport.addAction(self.actionExportKML)
        self.menuExport.addAction(self.actionExportCSV)
        self.menuExport.addAction(self.actionExportFilteredKML)
        self.menuExport.addAction(self.actionExportFilteredCSV)
        self.menuCreepy.addAction(self.menuNewProject.menuAction())
        self.menuCreepy.addAction(self.menuExport.menuAction())
        self.menuCreepy.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPluginsConfiguration)
        self.menuAbout.addAction(self.actionReportProblem)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionCheckUpdates)
        self.menuView.addSeparator()
        self.menuFilters.addAction(self.actionFilterLocationsCustom)
        self.menuFilters.addAction(self.actionFilterLocationsDate)
        self.menuFilters.addAction(self.actionFilterLocationsPosition)
        self.menuFilters.addAction(self.actionRemoveFilters)
        self.menuFilters.addAction(self.actionFilterInaccurateLocations)
        self.menubar.addAction(self.menuCreepy.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.mainToolbar.addAction(self.actionNewPersonProject)
        self.mainToolbar.addAction(self.actionNewPlaceProject)
        self.mainToolbar.addAction(self.actionPluginsConfiguration)
        self.mainToolbar.addAction(self.actionAnalyzeCurrentProject)
        self.mainToolbar.addAction(self.actionDrawCurrentProject)
        self.mainToolbar.addAction(self.actionExportKML)
        self.mainToolbar.addAction(self.actionExportCSV)
        self.mainToolbar.addSeparator()
        self.locationsActionsToolbar.addAction(self.actionFilterLocationsCustom)
        self.locationsActionsToolbar.addAction(self.actionFilterLocationsDate)
        self.locationsActionsToolbar.addAction(self.actionFilterLocationsPosition)
        self.locationsActionsToolbar.addAction(self.actionFilterInaccurateLocations)
        self.locationsActionsToolbar.addAction(self.actionShowHeatMap)
        self.locationsActionsToolbar.addAction(self.actionRemoveFilters)

        self.retranslateUi(CreepyMainWindow)
        self.centralStackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), CreepyMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(CreepyMainWindow)

    def retranslateUi(self, CreepyMainWindow):
        CreepyMainWindow.setWindowTitle(_translate("CreepyMainWindow", "cree.py - Geolocation OSINT tool", None))
        self.menuCreepy.setTitle(_translate("CreepyMainWindow", "Creepy", None))
        self.menuNewProject.setTitle(_translate("CreepyMainWindow", "New Project", None))
        self.menuExport.setTitle(_translate("CreepyMainWindow", "Export", None))
        self.menuEdit.setTitle(_translate("CreepyMainWindow", "Edit", None))
        self.menuAbout.setTitle(_translate("CreepyMainWindow", "Help", None))
        self.menuView.setTitle(_translate("CreepyMainWindow", "View", None))
        self.menuFilters.setTitle(_translate("CreepyMainWindow", "Filters", None))
        self.dockWLocationsList.setWindowTitle(_translate("CreepyMainWindow", "Locations List", None))
        self.dockWProjects.setWindowTitle(_translate("CreepyMainWindow", "Target Projects", None))
        self.dockWCurrentLocationDetails.setWindowTitle(_translate("CreepyMainWindow", "Current Location Details", None))
        self.currentTargetDetailsDetailsDateLabel.setText(_translate("CreepyMainWindow", "<b>Date:       </b>        ", None))
        self.currentTargetDetailsLocationLabel.setText(_translate("CreepyMainWindow", "<b>Location: </b>", None))
        self.currentTargetDetailsSourceLabel.setText(_translate("CreepyMainWindow", "<b>From:       <b>", None))
        self.currentTargetDetailsContextLabel.setText(_translate("CreepyMainWindow", "<b>Context:  <b>", None))
        self.mainToolbar.setWindowTitle(_translate("CreepyMainWindow", "toolBar", None))
        self.locationsActionsToolbar.setWindowTitle(_translate("CreepyMainWindow", "toolBar_2", None))
        self.dockWLogging.setWindowTitle(_translate("CreepyMainWindow", "Log Output", None))
        self.actionExportKML.setText(_translate("CreepyMainWindow", "Export Project Locations as KML", None))
        self.actionExportKML.setToolTip(_translate("CreepyMainWindow", "Export project locations in KML format", None))
        self.actionExportCSV.setText(_translate("CreepyMainWindow", "Export Project Locations as CSV", None))
        self.actionExportCSV.setToolTip(_translate("CreepyMainWindow", "Export project locations in CSV format", None))
        self.actionExit.setText(_translate("CreepyMainWindow", "Exit", None))
        self.actionReportProblem.setText(_translate("CreepyMainWindow", "Report a problem / bug", None))
        self.actionAbout.setText(_translate("CreepyMainWindow", "About", None))
        self.actionPluginsConfiguration.setText(_translate("CreepyMainWindow", "Plugins Configuration", None))
        self.actionLocations_List.setText(_translate("CreepyMainWindow", "Locations List", None))
        self.actionResult_Details.setText(_translate("CreepyMainWindow", "Result Details", None))
        self.actionAvailable_Plugins.setText(_translate("CreepyMainWindow", "Available Plugins", None))
        self.actionSettings.setText(_translate("CreepyMainWindow", "Settings", None))
        self.actionNewPersonProject.setText(_translate("CreepyMainWindow", "Person Based Project", None))
        self.actionNewLocationBasedProject.setText(_translate("CreepyMainWindow", "Location Based Project", None))
        self.actionAnalyzeCurrentProject.setText(_translate("CreepyMainWindow", "Analyze Current Project", None))
        self.actionAnalyzeCurrentProject.setToolTip(_translate("CreepyMainWindow", "Analyze Current Project", None))
        self.actionDrawCurrentProject.setText(_translate("CreepyMainWindow", "Draw Locations for Current Project", None))
        self.actionDrawCurrentProject.setToolTip(_translate("CreepyMainWindow", "Draw Locations for the currently selected project", None))
        self.actionFilterLocationsDate.setText(_translate("CreepyMainWindow", "Filter Locations by Date", None))
        self.actionFilterLocationsDate.setToolTip(_translate("CreepyMainWindow", "<html><head/><body><p>You can filter the retrieved locations from a project based on a date range within which they have been created</p></body></html>", None))
        self.actionFilterLocationsPosition.setText(_translate("CreepyMainWindow", "Filter Locations by Position", None))
        self.actionFilterLocationsPosition.setToolTip(_translate("CreepyMainWindow", "<html><head/><body><p>You can filter the retrieved locations based on their distance from a given point in the map</p></body></html>", None))
        self.actionRemoveFilters.setText(_translate("CreepyMainWindow", "Remove Filters", None))
        self.actionRemoveFilters.setToolTip(_translate("CreepyMainWindow", "<html><head/><body><p>Remove all the filters on date and locations and show all the retreived locations on the map</p></body></html>", None))
        self.actionShowHeatMap.setText(_translate("CreepyMainWindow", "Show HeatMap", None))
        self.actionShowHeatMap.setToolTip(_translate("CreepyMainWindow", "<html><head/><body><p>Show a heatmap with the selected locations instead of pointers.</p></body></html>", None))
        self.actionLocation_Actions.setText(_translate("CreepyMainWindow", "Location Actions", None))
        self.actionMain_Toolbar.setText(_translate("CreepyMainWindow", "Main Toolbar", None))
        self.actionDeleteCurrentProject.setText(_translate("CreepyMainWindow", "Delete Current Project", None))
        self.actionDeleteCurrentProject.setToolTip(_translate("CreepyMainWindow", "Delete this project", None))
        self.actionExportFilteredKML.setText(_translate("CreepyMainWindow", "Export Filtered Locations as KML", None))
        self.actionExportFilteredKML.setToolTip(_translate("CreepyMainWindow", "Export  currently visible locations as a KML file", None))
        self.actionExportFilteredCSV.setText(_translate("CreepyMainWindow", "Export Filtered Locations as CSV", None))
        self.actionExportFilteredCSV.setToolTip(_translate("CreepyMainWindow", "Export currently visible locations as CSV", None))
        self.actionReanalyzeCurrentProject.setText(_translate("CreepyMainWindow", "Reanalyze Current Project", None))
        self.actionReanalyzeCurrentProject.setToolTip(_translate("CreepyMainWindow", "Reanalyze Current Project", None))
        self.actionCheckUpdates.setText(_translate("CreepyMainWindow", "Check for updates", None))
        self.actionCompareProjects.setText(_translate("CreepyMainWindow", "Compare Projects", None))
        self.actionCompareProjects.setToolTip(_translate("CreepyMainWindow", "Compare two projects", None))
        self.actionFilterLocationsCustom.setText(_translate("CreepyMainWindow", "Filter Locations ( Custom ) ", None))
        self.actionNewPlaceProject.setText(_translate("CreepyMainWindow", "Place Based Project", None))
        self.actionFilterInaccurateLocations.setText(_translate("CreepyMainWindow", "Filter Inaccurate Locations", None))

from PyQt4 import QtWebKit
import creepy_resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CreepyMainWindow = QtGui.QMainWindow()
    ui = Ui_CreepyMainWindow()
    ui.setupUi(CreepyMainWindow)
    CreepyMainWindow.show()
    sys.exit(app.exec_())

