# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/placeProjectWizard.ui'
#
# Created: Wed Oct 14 17:30:49 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_placeProjectWizard(object):
    def setupUi(self, placeProjectWizard):
        placeProjectWizard.setObjectName(_fromUtf8("placeProjectWizard"))
        placeProjectWizard.resize(898, 702)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/user")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        placeProjectWizard.setWindowIcon(icon)
        placeProjectWizard.setWizardStyle(QtGui.QWizard.ClassicStyle)
        placeProjectWizard.setOptions(QtGui.QWizard.HelpButtonOnRight)
        self.placeProjectWizardPage1 = QtGui.QWizardPage()
        self.placeProjectWizardPage1.setObjectName(_fromUtf8("placeProjectWizardPage1"))
        self.gridLayoutWidget = QtGui.QWidget(self.placeProjectWizardPage1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 861, 591))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.placeProjectDescriptionValue = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.placeProjectDescriptionValue.setPlainText(_fromUtf8(""))
        self.placeProjectDescriptionValue.setObjectName(_fromUtf8("placeProjectDescriptionValue"))
        self.gridLayout_3.addWidget(self.placeProjectDescriptionValue, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 1)
        self.placeProjectNameValue = QtGui.QLineEdit(self.gridLayoutWidget)
        self.placeProjectNameValue.setObjectName(_fromUtf8("placeProjectNameValue"))
        self.gridLayout_3.addWidget(self.placeProjectNameValue, 0, 1, 1, 1)
        self.placeProjectNameLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.placeProjectNameLabel.setEnabled(True)
        self.placeProjectNameLabel.setObjectName(_fromUtf8("placeProjectNameLabel"))
        self.gridLayout_3.addWidget(self.placeProjectNameLabel, 0, 0, 1, 1)
        self.placeProjectKeywordsValue = QtGui.QLineEdit(self.gridLayoutWidget)
        self.placeProjectKeywordsValue.setObjectName(_fromUtf8("placeProjectKeywordsValue"))
        self.gridLayout_3.addWidget(self.placeProjectKeywordsValue, 1, 1, 1, 1)
        self.placeProjectDescriptionLabel = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placeProjectDescriptionLabel.sizePolicy().hasHeightForWidth())
        self.placeProjectDescriptionLabel.setSizePolicy(sizePolicy)
        self.placeProjectDescriptionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.placeProjectDescriptionLabel.setObjectName(_fromUtf8("placeProjectDescriptionLabel"))
        self.gridLayout_3.addWidget(self.placeProjectDescriptionLabel, 2, 0, 1, 1)
        self.personProkectKeywordsLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.personProkectKeywordsLabel.setObjectName(_fromUtf8("personProkectKeywordsLabel"))
        self.gridLayout_3.addWidget(self.personProkectKeywordsLabel, 1, 0, 1, 1)
        placeProjectWizard.addPage(self.placeProjectWizardPage1)
        self.placeProjectWizardPage2 = QtGui.QWizardPage()
        self.placeProjectWizardPage2.setObjectName(_fromUtf8("placeProjectWizardPage2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.placeProjectWizardPage2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 871, 571))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.containerLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.containerLayout.setMargin(0)
        self.containerLayout.setObjectName(_fromUtf8("containerLayout"))
        self.titleLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setTextFormat(QtCore.Qt.RichText)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.containerLayout.addWidget(self.titleLabel)
        self.webView = QtWebKit.QWebView(self.verticalLayoutWidget)
        self.webView.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.containerLayout.addWidget(self.webView)
        self.searchAddressLayout = QtGui.QHBoxLayout()
        self.searchAddressLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.searchAddressLayout.setObjectName(_fromUtf8("searchAddressLayout"))
        self.searchAddressLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.searchAddressLabel.setObjectName(_fromUtf8("searchAddressLabel"))
        self.searchAddressLayout.addWidget(self.searchAddressLabel)
        self.searchAddressInput = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.searchAddressInput.setInputMask(_fromUtf8(""))
        self.searchAddressInput.setObjectName(_fromUtf8("searchAddressInput"))
        self.searchAddressLayout.addWidget(self.searchAddressInput)
        self.searchAddressButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.searchAddressButton.setObjectName(_fromUtf8("searchAddressButton"))
        self.searchAddressLayout.addWidget(self.searchAddressButton)
        self.containerLayout.addLayout(self.searchAddressLayout)
        self.controlsContainerLayout = QtGui.QHBoxLayout()
        self.controlsContainerLayout.setObjectName(_fromUtf8("controlsContainerLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.controlsContainerLayout.addItem(spacerItem1)
        self.radiusLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiusLabel.sizePolicy().hasHeightForWidth())
        self.radiusLabel.setSizePolicy(sizePolicy)
        self.radiusLabel.setTextFormat(QtCore.Qt.RichText)
        self.radiusLabel.setObjectName(_fromUtf8("radiusLabel"))
        self.controlsContainerLayout.addWidget(self.radiusLabel)
        self.radiusSpinBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiusSpinBox.sizePolicy().hasHeightForWidth())
        self.radiusSpinBox.setSizePolicy(sizePolicy)
        self.radiusSpinBox.setMaximum(1000)
        self.radiusSpinBox.setObjectName(_fromUtf8("radiusSpinBox"))
        self.controlsContainerLayout.addWidget(self.radiusSpinBox)
        self.radiusUnitComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiusUnitComboBox.sizePolicy().hasHeightForWidth())
        self.radiusUnitComboBox.setSizePolicy(sizePolicy)
        self.radiusUnitComboBox.setObjectName(_fromUtf8("radiusUnitComboBox"))
        self.controlsContainerLayout.addWidget(self.radiusUnitComboBox)
        self.containerLayout.addLayout(self.controlsContainerLayout)
        placeProjectWizard.addPage(self.placeProjectWizardPage2)
        self.placeProjectWizardPage3 = QtGui.QWizardPage()
        self.placeProjectWizardPage3.setObjectName(_fromUtf8("placeProjectWizardPage3"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.placeProjectWizardPage3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 841, 601))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.containerLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.containerLayout_2.setMargin(0)
        self.containerLayout_2.setObjectName(_fromUtf8("containerLayout_2"))
        self.placeProjectSearchInLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.placeProjectSearchInLabel.setObjectName(_fromUtf8("placeProjectSearchInLabel"))
        self.containerLayout_2.addWidget(self.placeProjectSearchInLabel)
        self.placeProjectAvailablePluginsListView = QtGui.QListView(self.verticalLayoutWidget_2)
        self.placeProjectAvailablePluginsListView.setObjectName(_fromUtf8("placeProjectAvailablePluginsListView"))
        self.containerLayout_2.addWidget(self.placeProjectAvailablePluginsListView)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.containerLayout_2.addItem(spacerItem2)
        placeProjectWizard.addPage(self.placeProjectWizardPage3)
        self.placeProjectWizardPage4 = QtGui.QWizardPage()
        self.placeProjectWizardPage4.setObjectName(_fromUtf8("placeProjectWizardPage4"))
        self.placeProjectWizardSearchConfigPluginsList = QtGui.QListView(self.placeProjectWizardPage4)
        self.placeProjectWizardSearchConfigPluginsList.setGeometry(QtCore.QRect(0, 0, 256, 531))
        self.placeProjectWizardSearchConfigPluginsList.setObjectName(_fromUtf8("placeProjectWizardSearchConfigPluginsList"))
        self.searchConfiguration = QtGui.QStackedWidget(self.placeProjectWizardPage4)
        self.searchConfiguration.setGeometry(QtCore.QRect(260, 0, 591, 531))
        self.searchConfiguration.setObjectName(_fromUtf8("searchConfiguration"))
        placeProjectWizard.addPage(self.placeProjectWizardPage4)
        self.placeProjectWizardPage5 = QtGui.QWizardPage()
        self.placeProjectWizardPage5.setObjectName(_fromUtf8("placeProjectWizardPage5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.placeProjectWizardPage5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        placeProjectWizard.addPage(self.placeProjectWizardPage5)

        self.retranslateUi(placeProjectWizard)
        QtCore.QMetaObject.connectSlotsByName(placeProjectWizard)

    def retranslateUi(self, placeProjectWizard):
        placeProjectWizard.setWindowTitle(_translate("placeProjectWizard", "New Place Project", None))
        self.placeProjectWizardPage1.setTitle(_translate("placeProjectWizard", "Step 1 - Set Project Metadata", None))
        self.placeProjectWizardPage1.setSubTitle(_translate("placeProjectWizard", "Add project related information", None))
        self.placeProjectNameValue.setPlaceholderText(_translate("placeProjectWizard", "Add a name for your project", None))
        self.placeProjectNameLabel.setText(_translate("placeProjectWizard", "Project Name ", None))
        self.placeProjectKeywordsValue.setPlaceholderText(_translate("placeProjectWizard", "Add comma seperated keywords for your project", None))
        self.placeProjectDescriptionLabel.setText(_translate("placeProjectWizard", "Description", None))
        self.personProkectKeywordsLabel.setText(_translate("placeProjectWizard", "Keywords", None))
        self.placeProjectWizardPage2.setTitle(_translate("placeProjectWizard", "Step 2 - Set the target", None))
        self.placeProjectWizardPage2.setSubTitle(_translate("placeProjectWizard", "Select the Point Of Interest and the distance around which you want to get results", None))
        self.titleLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-size:9pt;\">Drop a </span><span style=\" font-size:9pt; font-weight:600; color:#ff0000;\">pin</span><span style=\" font-size:9pt;\"> on the map for your point of interest</span></p></body></html>", None))
        self.searchAddressLabel.setText(_translate("placeProjectWizard", "Address", None))
        self.searchAddressButton.setText(_translate("placeProjectWizard", "Search", None))
        self.radiusLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-size:9pt;\">Distance from the POI :</span></p></body></html>", None))
        self.placeProjectSearchInLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-weight:600;\">Search In</span></p></body></html>", None))
        self.placeProjectWizardPage4.setTitle(_translate("placeProjectWizard", "Step 3 - Set Parameters", None))
        self.placeProjectWizardPage4.setSubTitle(_translate("placeProjectWizard", "Provide the necessary search parameters for the plugins you are using", None))
        self.placeProjectWizardPage5.setTitle(_translate("placeProjectWizard", "Step 4  - Finalize Project", None))
        self.placeProjectWizardPage5.setSubTitle(_translate("placeProjectWizard", "Click Finish to save the Project Configuration ", None))

from PyQt4 import QtWebKit
import creepy_resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    placeProjectWizard = QtGui.QWizard()
    ui = Ui_placeProjectWizard()
    ui.setupUi(placeProjectWizard)
    placeProjectWizard.show()
    sys.exit(app.exec_())

